export const Localization = {
    en: {
        languageKey: 'en',
        /*Components*/
        startButton: 'TAP\n TO START',
        continueButton: 'Continue',
        completeButton: 'Complete',
        /*InfoWidget*/
        infoWidgetHeadline: 'Keep Your Phone Up-to-Date',
        infoWidgetText01: 'Learn how to update your phone\'s operating system and why it is so important in under 120 seconds!',
        infoWidgetText02: 'Updates often include optimizations that can help extend your phone\'s battery life.',
        infoWidgetText03: 'Updating your phone ensures you have the latest security patches, protecting your data from vulnerabilities.',
        infoWidgetSubText: 'Do it with your own smartphone now!',
        /*AnswerOption*/
        answerOptionText01: 'to fix security vulnerabilities',  
        answerOptionText02: 'to increase hardware wear and tear',
        answerOptionText03: 'to reduce free memory',
        answerOptionText04: 'to decrease battery life',
        answerOptionText05: 'to improve features and functionality',
        /*FinalWidget*/
        finalWidgetText01: 'Prevent possible security vulnerabilities',
        finalWidgetText02: 'Improved features and functinality',
        finalWidgetText03: 'Fixed possible bugs',
        finalWidgetText04: 'Ensured compatibility with other systems',
        /*SolutionOption*/
        solutionOptionText01: 'to fix security vulnerabilities',
        solutionOptionText02: 'to increase hardware wear and tear',
        solutionOptionText03: 'to reduce free memory',
        solutionOptionText04: 'to decrease battery life',
        solutionOptionText05: 'to improve features and functionality',
        solutionOptionSubText01: 'Updates fix security vulnerabilities that have arisen to offer you the safest experience.',
        solutionOptionSubText02: 'Updates have nothing to do with hardware wear and tear. They only affect the software.',
        solutionOptionSubText03: 'Updates actually need free memory but they free up memory from old updates after installation.',
        solutionOptionSubText04: 'Updates have little to no influence on battery life. On the contrary, sometimes they even increase it.',
        solutionOptionSubText05: 'Updates often bring new features to always offer the best experience. In addition they fix known bugs.',
        /*UpdateWarning*/
        updateWarningText: 'If you want to execute the following steps right now, make sure you are connected to Wi-Fi because Updates may be large.',
        /*WifiWarning*/
        wifiWarningText: 'From now on your mobile phone will try to install updates on its own as soon as it is connected to WI-FI.',
        /*InfoOverlay*/
        infoOverlayHeadline01: 'What is this?',
        infoOverlayHeadline02: 'What platform do I have?',
        infoOverlayHeadline03: 'How to find the Settings App?',
        infoOverlayHeadline04: 'How to find System and updates?',
        infoOverlayHeadline05: 'How to find Software update?',
        infoOverlayHeadline06: 'Error on Search for Update?',
        infoOverlayHeadline07: 'No Update option appears',
        infoOverlayHeadline08: 'A long text appears?',
        infoOverlayHeadline09: 'How to find General?',
        infoOverlayHeadline10: 'How to find Software Update?',
        infoOverlayText01: 'This application offers a quick and simple step by step guide on how to update your phone manually and how to enable the automatic update function.',
        infoOverlayText02: 'Turn your phone backwards. Look for an icon. If you find an apple like icon, your phone is an apple device. If you don\'t find any icon, choose Android.',
        infoOverlayText03: 'Look for the gear icon. Swipe down shortly from the top half of your screen. A searchbar appears. Type in \'Settings\' and choose the first result.',
        infoOverlayText04: 'Below the headline a search bar is placed. Type in System & updates and choose the first result.',
        infoOverlayText05: 'This option is always in first place in the list.',
        infoOverlayText06: 'Make sure your device is connected to the Wi-Fi. Swipe down to force a new search. A progress wheel will appear.',
        infoOverlayText07: 'It seems like your phone is already up-to-date.',
        infoOverlayText08: 'This is LEGAL (Licensed Application End User License Agreement). Sometimes you just have to accept it by clicking the button \'Accept\'.',
        infoOverlayText09: 'If you scroll to the top and swipe down a bit a search bar appears. Type in \'General\' and choose the first result.',
        infoOverlayText10: 'This option is always in second place in the list.',
        infoOverlayText11: 'Next to the headline a search symbol is placed. Type in Software update and choose the first result.',
        /*Screens*/
        /*InfoView & SolutionView*/
        infoViewHeadline: 'Why are Software Updates so important?',
        infoViewText01: 'What do you think?',
        infoViewText02: 'Choose one or more answers that you think are important.',
        /*PickerView*/
        pickerViewHeadline: '1. Choose Platform',
        pickerViewText01: 'Mobile phones provide the possibility to perform updates automatically.\nIn the following we will show you how to activate this and also how to perform an update manually.',
        pickerViewText02: 'Grab your phone and try this simultaneously on your own!',
        pickerViewText03: 'Please scan the QR-Code according to you platform to open the settings app on your smartphone and click on it to continue:',
        pickerViewText04: 'Did not work? Please continue here:',
        pickerViewText03WithoutQRCode: 'Please choose your platform here:',
        androidPickerText: 'Android may vary across different devices. Please choose your smartphone brand:',
        /*CelebViewAndroid & CelebViewiOS*/
        celebViewText: 'Congratulations!',
        /*StepViews iOS*/
        
        /*StepViews Huawei*/

        /*StepViews Samsung */
        stepViewText0101_Samsung: '1. Swipe from the top of your smartphone to open the Notification Panel.',
        stepViewText0102_Samsung: '2. Open the Settings App.',
        stepViewText0103_Samsung: '3. Go to <i>Software update</i>.',
        stepViewText0201_Samsung: '1. If not enabled, activate <i>Auto download over Wi-Fi</i>.',
        stepViewText0301_Samsung: '1. Once you have enabled the Automatic Update function, go to <i>Download and install</i>. Your phone starts searching for updates.',
        stepViewText0302_Samsung: '2. If an update is available, the download will start automatically. Otherwise, you are already up to date.',
        stepViewText0303_Samsung: '3. After the download click on <i>Install now</i> to start the update immediately. It may take some time until it\'s finished.',

        stepViewHeadline01: '1. Find the Update Settings',
        stepViewText0101: '1. Search for your <i>Settings App</i>.',
        stepViewText0101QRCode: '1. Scan the QR-Code to open the <i>Settings App</i> on your smartphone:',
        stepViewText0102Android: '2. Scroll to <i>System & updates</i>.',
        stepViewText0102iOS: '2. Go to <i>General</i>.',
        stepViewText0103Android: '3. Go to <i>Software update</i>.',
        stepViewText0103iOS: '3. Go to <i>Software Update</i>.',
        stepViewHeadline02: '2. Enable Automatic Update',
        stepViewText0201Android: '1. Click on the gear icon.',
        stepViewText0201iOS: '1. Go to <i>Automatic Updates</i>.',
        stepViewText0202: '2. If not enabled, activate <i>all</i> options.',
        stepViewHeadline03: '3. Search for Updates',
        stepViewText0301: '1. Once you have enabled the Automatic Update function, go one step back to the Software Update tab. Your phone starts searching for updates.',
        stepViewText0302iOS: '2. If an update is available, it is displayed as on the right, otherwise nothing appears and you are already up to date.',
        stepViewText0302Android: '2. If an update is available, it is displayed similarly to the right. Otherwise, you are already up to date.',
        stepViewText0303iOS: '3. Click on <i>Update Now</i> to start the update immediately. It may take some time until it\'s finished.',
        stepViewText0303Android: '3. Click on <i>New version</i> to start the update immediately. It may take some time until it\'s finished.',
        /*FinalViews*/
        finalViewHeadline: 'Congratulations!',
        finalViewText: 'You performed an important and major security action!',
    },
    de: {
        languageKey: 'de',
        /*Components*/
        startButton: 'TIPPE\n HIER',
        continueButton: 'Weiter',
        completeButton: 'Abschließen',
        /*InfoWidget*/
        infoWidgetHeadline: 'Halte dein Handy Up-to-Date',
        infoWidgetText01: 'Lerne in unter 120 Sekunden, wie du dein Smartphone aktualisierst und warum das so wichtig ist!',
        infoWidgetText02: 'Updates enthalten oft Optimierungen, die die Akkulaufzeit deines Handys verlängern können.',
        infoWidgetText03: 'Durch Updates stellst du sicher, dass du und deine Daten gegen Schwachstellen geschützt sind.',
        infoWidgetSubText: 'Versuche es jetzt mit deinem Smartphone!',
        /*AnswerOption*/
        answerOptionText01: 'um Sicherheitslücken zu beheben',  
        answerOptionText02: 'um den Verschleiß der Hardware zu fördern',
        answerOptionText03: 'um freien Speicher zu reduzieren',
        answerOptionText04: 'um die Akkulaufzeit zu verringern',
        answerOptionText05: 'um Funktionen und Leistung zu verbessern',
        /*FinalWidget*/
        finalWidgetText01: 'Mögliche Sicherheitslücken wurden behoben',
        finalWidgetText02: 'Funktionen und Leistung wurden verbessert',
        finalWidgetText03: 'Mögliche Fehler wurden behoben',
        finalWidgetText04: 'Kompatibilität mit anderen Systemen wurde sichergestellt',
        /*SolutionOption*/
        solutionOptionText01: 'um Sicherheitslücken zu beheben',
        solutionOptionText02: 'um den Verschleiß der Hardware zu fördern',
        solutionOptionText03: 'um freien Speicher zu reduzieren',
        solutionOptionText04: 'um die Akkulaufzeit zu verringern',
        solutionOptionText05: 'um Funktionen und Leistung zu verbessern',
        solutionOptionSubText01: 'Updates beheben Sicherheitslücken, die aufgetreten sind, um dir das sicherste Erlebnis zu bieten.',
        solutionOptionSubText02: 'Updates haben nichts mit dem Verschleiß der Hardware zu tun. Sie beeinflussen nur die Software.',
        solutionOptionSubText03: 'Updates benötigen tatsächlich freien Speicher, geben aber nach der Installation wieder Speicher frei.',
        solutionOptionSubText04: 'Updates haben wenig bis keinen Einfluss auf die Akkulaufzeit. Manchmal erhöhen sie sie sogar.',
        solutionOptionSubText05: 'Updates enthalten oft neue Funktionen. Außerdem beheben sie bekannte Fehler.',
        /*UpdateWarning*/
        updateWarningText: 'Wenn du die folgenden Schritte jetzt ausführen möchtest, stelle sicher, dass du mit einem WLAN verbunden bist, um eine hohe Datennutzung zu vermeiden.',
        /*WifiWarning*/
        wifiWarningText: 'Von jetzt an wird dein Smartphone versuchen Updates automatisch zu installieren, sobald eine WLAN-Verbindung besteht.',
        /*InfoOverlay*/
        infoOverlayHeadline01: 'Was ist das hier?',
        infoOverlayHeadline02: 'Welche Plattform habe ich?',
        infoOverlayHeadline03: 'Wie finde ich Einstellungen?',
        infoOverlayHeadline04: 'Wo ist System & Updates?',
        infoOverlayHeadline05: 'Wo ist Softwareupdate?',
        infoOverlayHeadline06: 'Fehler bei der Suche nach Updates?',
        infoOverlayHeadline07: 'Kein Upate verfügbar?',
        infoOverlayHeadline08: 'Erscheint ein langer Text?',
        infoOverlayHeadline09: 'Wie finde ich Allgemein?',
        infoOverlayHeadline10: 'Wo ist Softwareupdate?',
        infoOverlayText01: 'Diese Anwendung bietet dir ein kurzes Step-By-Step Tutorial, wie du dein Smartphone manuell aktualisierst und die automatische Update Funktion aktivierst.',
        infoOverlayText02: 'Drehe dein Smartphone. Suche nach Icons. Wenn du ein Icon in Form eines Apfels findest, ist dein Gerät von Apple. Andernfalls wähle Android.',
        infoOverlayText03: 'Suche nach dem Zahnrad Icon. Ziehe kurz von der oberen Hälfte deines Bildschirms nach unten. Eine Suchleiste erscheint. Tippe \'Einstellungen\' ein und wähle das erste Ergebnis.',
        infoOverlayText04: 'Unter der Überschrift ist eine Suchleiste platziert. Tippe System & Updates ein und wähle das erste Ergebnis.',
        infoOverlayText05: 'Diese Option ist immer an erster Stelle in der Liste.',
        infoOverlayText06: 'Stelle sicher, dass dein Gerät mit dem WLAN verbunden ist. Ziehe nach unten um die Suche nach Updates zu starten.',
        infoOverlayText07: 'Es scheint als wäre dein Smartphone bereits auf dem neuesten Stand.',
        infoOverlayText08: 'Das ist das LEGAL (Licensed Application End User License Agreement). Manchmal musst du es vor einem Update durch ein Klicken auf einen Button akzeptieren.',
        infoOverlayText09: 'Wenn du nach oben scrollst und ein wenig nach unten ziehst, erscheint eine Suchleiste. Tippe \'Allgemein\' ein und wähle das erste Ergebnis.',
        infoOverlayText10: 'Diese Option ist immer an zweiter Stelle in der Liste.',
        infoOverlayText11: 'Neben der Überschrift ist eine Lupe platziert. Tippe dort Software-Update ein und wähle das erste Ergebnis.',
        /*Screens*/
        /*InfoView & SolutionView*/
        infoViewHeadline: 'Warum sind Softwareupdates so wichtig?',
        infoViewText01: 'Was denkst du?',
        infoViewText02: 'Wähle eine oder mehrere Optionen, die du für wichtig hältst.',
        /*PickerView*/
        pickerViewHeadline: '1. Wähle deine Plattform',
        pickerViewText01: 'Smartphones bieten uns die Möglichkeit Updates automatisch zu installieren.\nIm Folgenden zeigen wir dir, wie du diese Funktion aktivierst und auch wie du ein Update manuell durchführst.',
        pickerViewText02: 'Nimm dein Smartphone und versuche es nebenbei!',
        pickerViewText03: 'Bitte scanne den QR-Code für dein Betriebssystem um die Einstellungen zu öffnen. Klicke danach auf den QR-Code um fortzufahren:',
        pickerViewText04: 'Nicht geklappt? Dann wähle hier:',
        pickerViewText03WithoutQRCode: 'Bitte wähle hier dein Betriebssystem:',
        androidPickerText: 'Android kann sich auf verschiedenen Geräten unterscheiden. Bitte wähle deine Handymarke:',
        /*CelebViewAndroid & CelebViewiOS*/
        celebViewText: 'Gratulation!',
        /*StepViews iOS*/

        /*StepViews Huawei*/

        /*StepViews Samsung */
        stepViewText0101_Samsung: '1. Wische von oben nach unten, um das Benachrichtigungsfeld zu öffnen.',
        stepViewText0102_Samsung: '2. Öffne die Einstellungen.',
        stepViewText0103_Samsung: '3. Gehe zu <i>Software-Update</i>.',
        stepViewText0201_Samsung: '1. Wenn nicht aktiviert, aktiviere <i>Automatisch über WLAN laden</i>.',
        stepViewText0301_Samsung: '1. Sobald du die Funktion für Automatische Updates aktiviert hast, gehe zu <i>Herunterladen und installieren</i>. Die Suche nach Updates beginnt.',
        stepViewText0302_Samsung: '2. Wenn ein Update verfügbar ist, beginnt das Herunterladen automatisch. Andernfalls bist du bereits up-to-date.',
        stepViewText0303_Samsung: '3. Klicke auf <i>Jetzt installieren</i> um das Update sofort zu starten. Manchmal braucht es ein wenig Zeit bis das Update abgeschlossen ist.',

        stepViewHeadline01: '1. Update Einstellungen finden',
        stepViewText0101: '1. Suche die App <i>Einstellungen</i>.',
        stepViewText0101QRCode: '1. Scanne den QR-Code um die Einstellungen zu öffnen:',
        stepViewText0102Android: '2. Scrolle zu <i>System & Aktualisierungen</i>.',
        stepViewText0102iOS: '2. Gehe zu <i>Allgemein</i>.',
        stepViewText0103Android: '3. Gehe zu <i>Softwareaktualisierung</i>.',
        stepViewText0103iOS: '3. Gehe zu <i>Softwareupdate</i>.',
        stepViewHeadline02: '2. Aktivieren automatischer Updates',
        stepViewText0201Android: '1. Klicke auf das Zahnrad Icon.',
        stepViewText0201iOS: '1. Gehe zu <i>Automatische Updates</i>.',
        stepViewText0202: '2. Wenn nicht aktiviert, aktiviere <i>alle Optionen</i>.',
        stepViewHeadline03: '3. Suche nach Updates',
        stepViewText0301: '1. Sobald du die Funktion für Automatische Updates aktiviert hast, gehe einen Schritt zurück. Die Suche nach Updates beginnt.',
        stepViewText0302iOS: '2. Wenn ein Update verfügbar ist, wird es wie rechts dargestellt, ansonsten bist du bereits up-to-date.',
        stepViewText0302Android: '2. Wenn ein Update verfügbar ist, wird es ähnlich wie rechts dargestellt. Andernfalls bist du bereits up-to-date.',
        stepViewText0303iOS: '3. Klicke auf <i>Jetzt Aktualisieren</i> um das Update sofort zu starten. Manchmal braucht es ein wenig Zeit bis das Update abgeschlossen ist.',
        stepViewText0303Android: '3. Klicke auf <i>Neue Version</i> um das Update sofort zu starten. Manchmal braucht es ein wenig Zeit bis das Update abgeschlossen ist.',
        /*FinalViews*/
        finalViewHeadline: 'Gratulation!',
        finalViewText: 'Du hast dein Smartphone ein Stück sicherer gemacht!',
    },
}